# Tensors 

In [1]:
import torch


## zeros()

In [2]:
w=torch.zeros(3,4)
w

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## size() and shape

In [3]:
w.size()

torch.Size([3, 4])

In [4]:
w.shape

torch.Size([3, 4])

## randn() and randn_like()

In [5]:
w=torch.randn(4,3)
w

tensor([[ 0.8795, -1.4886,  0.7657],
        [-0.9975, -0.5712,  1.9866],
        [-0.3172,  0.1349,  0.7556],
        [ 0.4212, -1.1905,  0.1397]])

In [6]:
t=torch.randn_like(w)
t

tensor([[ 0.8260,  0.5194, -0.6942],
        [ 0.3607,  1.6914, -0.3025],
        [-2.2523, -0.1140, -1.0716],
        [ 0.0446, -0.6895, -0.0833]])

## fill_()

Any function that will change the tensor uses underscore with it (like fill_)

In [7]:
t.fill_(2)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

## view()

In order to reshape the tensor use view(i,j) where i,j are the reshape parameters 

In [8]:
t

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [9]:
t.view(3,-1)  # automatically find the another parameter that could be fitted use -1 as one of the argument

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [10]:
t.view(-1,4)  

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

## numpy()

To change tensor to the numpy array use numpy(), if tensors works on cpu, both tensor and numpy will share the memory location.

In [8]:
numpy_arrary=w.numpy()
numpy_arrary

array([[ 0.8794872 , -1.4885504 ,  0.765697  ],
       [-0.9975494 , -0.5712027 ,  1.9866251 ],
       [-0.3172225 ,  0.13486724,  0.7556106 ],
       [ 0.42124888, -1.1904967 ,  0.13972262]], dtype=float32)

In [9]:
type(numpy_arrary)

numpy.ndarray

# Classes

In [10]:
# Setting seeds to try and ensure we have the same results - this is not guaranteed across PyTorch releases.
import torch
torch.manual_seed(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

import numpy as np
np.random.seed(0)

In [11]:
import torchvision

In [12]:
import torch
from torchvision import datasets, transforms
import torch.nn.functional as F
from torch import nn

mean, std = (0.5,), (0.5,)

# Create a transform and normalise data
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize(mean, std)
                              ])

# Download FMNIST training dataset and load training data
trainset = datasets.FashionMNIST('~/.pytorch/FMNIST/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

# Download FMNIST test dataset and load test data
testset = datasets.FashionMNIST('~/.pytorch/FMNIST/', download=True, train=False, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

Extracting /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw/train-images-idx3-ubyte.gz to /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw


Extracting /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw/train-labels-idx1-ubyte.gz to /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw


Extracting /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw


Extracting /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to /Users/takshshilarawat/.pytorch/FMNIST/FashionMNIST/raw
Processing...
Done!


../torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
